# Training hyperparameters
batch_size: 64
lr: 0.001
epochs: 50
patience: 15
delta: 0.0001
seed: 42
device: "cuda"
num_workers: 2
resume: false
save_model: true

# Dataset configuration
dataset:
  name: "cifar10"
  augment: "none"

# Model configuration
model:
  name: "cnn"
  params:
    num_filters: 16       
    num_blocks: 4           
    dropout_rate: 0.0
    use_batch_norm: false
    skip: false           
    input_size: [32, 32]
    channels: 3
    name: "cnn_medium_cifar10"

# Weights & Biases configuration
wandb:
  enabled: true
  project: "deep-learning-application"
  entity: "martina-buccioni98-unifi"
  run_name: "cnn_medium_agu"
  log_images_every: 10

# Model saving
save_dir: "models/saved/cnn"
