# config.yaml - PGD Attack
dataset:
  name: "cifar10"
  batch_size: 64
  sample_id: 15
  augment: false

model:
  name: "cnn"
  checkpoint_path: "models/cnn_deep_skip_cifar10.pt"  
  params:
    num_filters: 16         
    num_blocks: 7                          
    dropout_rate: 0.2     
    use_batch_norm: false 
    skip: true            
    input_size: [32, 32] 
    channels: 3   

attack:
  type: "pgd"
  epsilon: 0.031  
  budget: 0.062   
  iterations: 10  
  targeted: false
  targeted_class: 6

output:
  base_dir: "proj4/output_adv/pgd"
  save_diff: true

device: 'cpu'
num_workers: 2
   